// Renders the extension's webview UIs (sidebar + results panel) to standalone
// HTML files in test/preview/ so you can iterate on the UI in a browser with NO
// extension-host reload.
//
// Usage:
//   node test/preview-ui.js
//   npm run preview:ui
//
// Then open test/preview/index.html (or any generated file) in a browser, or run
// "Simple Browser: Show" in VS Code and point it at a local server serving the
// folder (e.g. `npx serve test/preview`).

const fs = require('node:fs');
const path = require('node:path');

const root = path.join(__dirname, '..');
const outDir = path.join(__dirname, 'preview');
fs.mkdirSync(outDir, { recursive: true });

// --- Minimal vscode stub so the UI modules can be required outside VS Code ---
const settings = {
  pythonCommand: 'C:/envs/databricks/Scripts/python.exe',
  tempFolder: '.spark-cell-runner',
  injectDatabricksBootstrap: true,
  databricksProfile: 'DEV',
  clusterId: '1001-223344-abcd12',
  useServerless: false,
  workspacePathMappings: {},
  secretValues: {},
  widgetValues: { env: 'prod' },
  openPyFilesAsNotebook: true,
};

const SAMPLE_WIDGET_SOURCE = [
  'dbutils.widgets.text("env", "dev", "Environment")',
  'dbutils.widgets.dropdown("region", "eu", ["eu", "us", "ap"], "Region")',
  'dbutils.widgets.multiselect("markets", "US", ["US", "EU", "APAC"], "Markets")',
].join('\n');

const activeNotebookEditor = {
  notebook: {
    uri: { fsPath: 'C:/work/test/sample-notebook.py', path: 'C:/work/test/sample-notebook.py', scheme: 'file', toString() { return this.fsPath; } },
    getCells() {
      return SAMPLE_WIDGET_SOURCE.split('\n').map((text) => ({
        document: { getText: () => text },
      }));
    },
  },
};

const activeTextEditor = {
  document: {
    uri: { fsPath: 'C:/work/test/sample-notebook.py', path: 'C:/work/test/sample-notebook.py', scheme: 'file', toString() { return this.fsPath; } },
  },
};

function makeVscodeStub({ notebookActive }) {
  return {
    workspace: {
      getConfiguration() {
        return {
          get(key, defaultValue) {
            const value = settings[key];
            return value === undefined ? defaultValue : value;
          },
          update: async () => {},
        };
      },
      asRelativePath(uri) {
        return 'test/sample-notebook.py';
      },
      workspaceFolders: [{ uri: { fsPath: 'C:/work' } }],
    },
    window: {
      activeNotebookEditor: notebookActive ? activeNotebookEditor : undefined,
      activeTextEditor: notebookActive ? activeTextEditor : undefined,
    },
  };
}

const Module = require('module');
const origResolve = Module._resolveFilename;
Module._resolveFilename = function (request, ...args) {
  if (request === 'vscode') return 'vscode-stub';
  return origResolve.call(this, request, ...args);
};

function loadSidebar(stub) {
  require.cache['vscode-stub'] = { id: 'vscode-stub', filename: 'vscode-stub', loaded: true, exports: stub };
  Object.keys(require.cache)
    .filter((name) => name.includes(path.join(root, 'src')))
    .forEach((name) => delete require.cache[name]);
  return require(path.join(root, 'src', 'ui', 'sidebar.js'));
}

// --- 1. Sidebar: workspace view, idle state --------------------------------
const sidebarIdle = loadSidebar(makeVscodeStub({ notebookActive: false }));
fs.writeFileSync(path.join(outDir, 'sidebar-workspace-idle.html'), sidebarIdle.getSidebarHtml('workspace'), 'utf8');

// --- 2. Sidebar: workspace view, active notebook with widgets --------------
const sidebarActive = loadSidebar(makeVscodeStub({ notebookActive: true }));
fs.writeFileSync(path.join(outDir, 'sidebar-workspace-active.html'), sidebarActive.getSidebarHtml('workspace'), 'utf8');

// --- 3. Sidebar: settings view ----------------------------------------------
fs.writeFileSync(path.join(outDir, 'sidebar-settings.html'), sidebarActive.getSidebarHtml('settings'), 'utf8');

// --- 4. Results panel --------------------------------------------------------
{
  const stub = makeVscodeStub({ notebookActive: true });
  require.cache['vscode-stub'] = { id: 'vscode-stub', filename: 'vscode-stub', loaded: true, exports: stub };
  Object.keys(require.cache)
    .filter((name) => name.includes(path.join(root, 'src')))
    .forEach((name) => delete require.cache[name]);
  const resultPanel = require(path.join(root, 'src', 'ui', 'resultPanel.js'));

  const payload = {
    built: {
      label: 'Databricks cell 4',
      script: '# Generated by Databricks Cell Runner from sample-notebook.py\n\ntry:\n    # Cell 4\n    print(f"x = {x}")\n\nexcept DCRNotebookExit as __dcr_notebook_exit:\n',
    },
    result: {
      exitCode: 1,
      stdout: 'x = 42\n',
      stderr: 'Traceback (most recent call last):\n  File "<string>", line 4, in <module>\nNameError: name \'y\' is not defined\n',
    },
    resultText: 'Label: Databricks cell 4\nScript: .spark-cell-runner/sample-notebook.cell-4.py\nExit Code: 1\n\nSTDOUT\nx = 42\n\nSTDERR\nNameError: name \'y\' is not defined\n',
    resultPath: '.spark-cell-runner/sample-notebook.cell-4.result.txt',
    scriptPath: '.spark-cell-runner/sample-notebook.cell-4.py',
  };

  fs.writeFileSync(path.join(outDir, 'result-panel.html'), resultPanel.getRunResultHtml(payload), 'utf8');
}

// --- index.html linking everything ------------------------------------------
fs.writeFileSync(path.join(outDir, 'index.html'), `<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><title>Databricks Cell Runner — UI previews</title>
<style>
  body { font-family: sans-serif; max-width: 640px; margin: 40px auto; padding: 0 16px; }
  li { margin: 8px 0; }
  code { background: #eee; padding: 2px 5px; border-radius: 4px; }
</style></head>
<body>
<h1>Databricks Cell Runner — UI previews</h1>
<p>Regenerate with <code>npm run preview:ui</code>. Open in a browser; no extension reload needed.</p>
<ul>
  <li><a href="sidebar-workspace-idle.html">Sidebar — Workspace (idle)</a></li>
  <li><a href="sidebar-workspace-active.html">Sidebar — Workspace (notebook active, widgets)</a></li>
  <li><a href="sidebar-settings.html">Sidebar — Settings</a></li>
  <li><a href="result-panel.html">Run results panel (failure example)</a></li>
</ul>
<p>Note: in a plain browser the CSS variables fall back to defaults, so colors differ
slightly from VS Code's themed sidebar.</p>
</body></html>`, 'utf8');

console.log('UI previews written to test/preview/:');
for (const file of fs.readdirSync(outDir).sort()) {
  console.log('  ' + path.join('test', 'preview', file));
}
