// Local lakehouse container stack. Launches the active pool's warehouse as a
// Docker Compose / Podman stack (FileBrowser web UI over the warehouse
// directory) so the local Delta warehouse is visible and manageable from
// Docker Desktop or Podman Desktop.
//
// Note: this stack used MinIO, but MinIO revoked anonymous access to its
// container images (quay.io now returns 401 and the Docker Hub org is gone),
// so it pivoted to filebrowser/filebrowser, which serves the same purpose —
// browsing the warehouse — without any image-availability risk. Compute keeps
// running natively through the Sail pool; no JVM images are pulled.

const os = require('node:os');
const path = require('node:path');
const fs = require('node:fs');
const net = require('node:net');
const { execFile } = require('node:child_process');

const UI_PORT = 8080;
let runtimeCache = { runtime: undefined, checkedAt: 0 };
let stackStatusCache = { running: false, checkedAt: 0, poolName: undefined };

function getWarehouseRoot() {
  return path.join(os.homedir(), '.spark-cell-runner', 'warehouse');
}

function getComposeFilePath(poolName) {
  return path.join(getWarehouseRoot(), poolName, 'docker-compose.yml');
}

function getComposeProjectName(poolName) {
  return `spark-cell-runner-${poolName}`;
}

function probePort(port, host = '127.0.0.1', timeoutMs = 600) {
  return new Promise((resolve) => {
    const socket = net.connect({ port, host });
    const done = (ok) => {
      socket.destroy();
      resolve(ok);
    };
    socket.setTimeout(timeoutMs);
    socket.once('connect', () => done(true));
    socket.once('timeout', () => done(false));
    socket.once('error', () => done(false));
  });
}

function exec(runtime, args, timeoutMs = 120000) {
  return new Promise((resolve) => {
    execFile(runtime, args, { windowsHide: true, timeout: timeoutMs }, (error, stdout, stderr) => {
      resolve({ ok: !error, stdout: String(stdout || ''), stderr: String(stderr || ''), error });
    });
  });
}

// Detects docker first, then podman; cached for 60s so sidebar renders stay cheap.
async function detectRuntime() {
  if (runtimeCache.runtime && Date.now() - runtimeCache.checkedAt < 60000) {
    return runtimeCache.runtime;
  }

  let runtime = null;

  for (const candidate of ['docker', 'podman']) {
    const result = await exec(candidate, ['--version'], 15000);
    if (result.ok) {
      runtime = candidate;
      break;
    }
  }

  runtimeCache = { runtime, checkedAt: Date.now() };
  return runtime;
}

function getDbFilePath(poolName) {
  return path.join(getWarehouseRoot(), poolName, '.filebrowser.db');
}

// The UI port is picked once (first launch) and persisted in the compose file
// so later launches and the status probe reuse it — unless something else has
// grabbed it since (we never hardcode 8080 for a new pool).
function findFreePort() {
  return new Promise((resolve, reject) => {
    const server = net.createServer();
    server.unref();
    server.on('error', reject);
    server.listen(0, '127.0.0.1', () => {
      const { port } = server.address();
      server.close(() => resolve(port));
    });
  });
}

async function getUiPort(pool) {
  const composeFile = getComposeFilePath(pool.name);

  try {
    const existing = fs.readFileSync(composeFile, 'utf8');
    const match = existing.match(/-\s*"(\d+):\d+"/);
    if (match) {
      return Number(match[1]);
    }
  } catch {
    // No compose file yet — pick a free port below.
  }

  return findFreePort();
}

// True when OUR compose service is currently running (as opposed to the port
// being held by an unrelated process).
async function isStackRunning(runtime, composeFile, projectName) {
  const result = await exec(
    runtime,
    ['compose', '-f', composeFile, '-p', projectName, 'ps', '--services', '--filter', 'status=running'],
    30000
  );
  return result.ok && /lakehouse-browser/.test(result.stdout);
}

function buildComposeYaml(pool, port) {
  const warehouse = pool.warehousePath.replace(/\\/g, '/');
  const dbFile = getDbFilePath(pool.name).replace(/\\/g, '/');

  return `# Generated by Spark Cell Runner. Mounts the local Delta warehouse of
# pool "${pool.name}" into FileBrowser so it is browsable from Docker/Podman Desktop.
# Runs in noauth mode: the warehouse is already a plain local folder, so a login
# adds no protection — do NOT use this stack to expose files beyond localhost.
name: ${getComposeProjectName(pool.name)}

services:
  lakehouse-browser:
    image: docker.io/filebrowser/filebrowser:latest
    container_name: scr-lakehouse-${pool.name}
    command: ["-d", "/database/filebrowser.db", "-r", "/data", "-a", "0.0.0.0", "-p", "${port}"]
    ports:
      - "${port}:${port}"
    volumes:
      - ${warehouse}:/data
      - ${dbFile}:/database/filebrowser.db
    restart: unless-stopped
`;
}

async function composeArgs(composeFile, projectName, action) {
  // docker: `docker compose -f <file> -p <project> up -d`
  // podman: `podman compose ...` delegates to an installed compose provider.
  return ['compose', '-f', composeFile, '-p', projectName, ...action];
}

// Status heuristic: the FileBrowser port being open means the stack is up.
// Kept async + cached so sidebar renders never block on it.
async function refreshStackStatus(poolName, port) {
  let running = false;

  if (poolName && port && (await probePort(port))) {
    running = true;
  }

  stackStatusCache = {
    running,
    checkedAt: Date.now(),
    poolName: running ? poolName : undefined,
    port: running ? port : stackStatusCache.port,
  };
  return stackStatusCache;
}

function getCachedStackStatus() {
  return stackStatusCache;
}

// FileBrowser (original project, now archived) generates a random admin
// password on first boot and enforces 12+ character passwords, so fixed
// admin/admin is impossible. Instead the extension OWNS the credentials:
// a password is generated once, stored next to the warehouse, and re-applied
// to the FileBrowser database on every launch while the server is stopped
// (the bolt db is single-writer, so user management must run offline).

function getCredentialsFilePath(poolName) {
  return path.join(getWarehouseRoot(), poolName, '.filebrowser-credentials.txt');
}

function ensureCredentials(pool) {
  const file = getCredentialsFilePath(pool.name);

  try {
    const existing = fs.readFileSync(file, 'utf8');
    const match = existing.match(/^password:\s*(\S+)\s*$/m);
    if (match) {
      return { username: 'admin', password: match[1], file };
    }
  } catch {
    // First launch — generate below.
  }

  const password = `scr-${require('node:crypto').randomBytes(12).toString('hex')}`;
  fs.writeFileSync(
    file,
    `# FileBrowser login for the Spark Cell Runner lakehouse stack (pool "${pool.name}").\n`
    + `# The extension re-applies this password on every launch; edit the line below\n`
    + `# and relaunch to change it.\n`
    + `username: admin\n`
    + `password: ${password}\n`,
    'utf8'
  );

  return { username: 'admin', password, file };
}

async function seedUser(runtime, composeFile, projectName, username, password) {
  const runs = [
    ['-d', '/database/filebrowser.db', 'config', 'init'],
    ['-d', '/database/filebrowser.db', 'users', 'update', username, '--password', password],
    ['-d', '/database/filebrowser.db', 'users', 'add', username, password, '--perm.admin'],
  ];

  // config init is best-effort ("already exists" is fine); of the two user
  // commands exactly one applies (update when the user exists, add when not).
  const details = [];
  for (const [index, args] of runs.entries()) {
    const result = await exec(
      runtime,
      ['compose', '-f', composeFile, '-p', projectName, 'run', '--rm', '-T', 'lakehouse-browser', ...args],
      120000
    );

    if (result.ok) {
      continue;
    }

    const detail = (result.stderr || result.stdout || result.error.message).trim();

    if (index === 0 || !/already exists|not found|too short|invalid/i.test(detail)) {
      details.push(detail.split('\n')[0]);
    }
  }

  return details;
}

// Checks the credentials against FileBrowser's own login API.
async function verifyLogin(port, username, password) {
  try {
    const response = await fetch(`http://localhost:${port}/api/login`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ username, password }),
    });
    return response.status === 200;
  } catch {
    return false;
  }
}

async function launchLakehouse(pool, output) {
  const runtime = await detectRuntime();

  if (!runtime) {
    throw new Error(
      'Neither Docker nor Podman was found. Install Docker Desktop or Podman Desktop, then try again.'
    );
  }

  fs.mkdirSync(pool.warehousePath, { recursive: true });
  const composeFile = getComposeFilePath(pool.name);
  const projectName = getComposeProjectName(pool.name);

  let port = await getUiPort(pool);
  const wasRunning = fs.existsSync(composeFile) && (await isStackRunning(runtime, composeFile, projectName));

  if (!wasRunning && (await probePort(port))) {
    // Persisted port now belongs to some other process — pick a fresh one.
    port = await findFreePort();
  }

  fs.writeFileSync(composeFile, buildComposeYaml(pool, port), 'utf8');

  const dbFile = getDbFilePath(pool.name);

  if (!fs.existsSync(dbFile)) {
    // 0-byte file: bbolt initializes a new database in it on first open, and
    // Docker binds it as a file instead of creating a directory.
    fs.writeFileSync(dbFile, '');
  }

  const credentials = ensureCredentials(pool);

  if (output) {
    output.appendLine(`[lakehouse] launching ${runtime} stack for pool "${pool.name}" (${composeFile})...`);
  }

  // User management must run offline (single-writer bolt db).
  if (!wasRunning) {
    const seedIssues = await seedUser(runtime, composeFile, projectName, credentials.username, credentials.password);

    if (seedIssues.length && output) {
      output.appendLine(`[lakehouse] credential seeding warnings: ${seedIssues.join(' | ')}`);
    }
  }

  const result = await exec(runtime, ['compose', '-f', composeFile, '-p', projectName, 'up', '-d'], 300000);

  if (!result.ok) {
    throw new Error(
      `${runtime} compose up failed: ${(result.stderr || result.error.message).trim()}`
    );
  }

  // Give the UI a moment to bind before probing.
  const deadline = Date.now() + 15000;
  while (Date.now() < deadline) {
    if (await probePort(port)) {
      break;
    }
    await new Promise((resolve) => setTimeout(resolve, 500));
  }

  await refreshStackStatus(pool.name, port);

  // The port binds before the app is ready to serve requests, and first boot
  // (fresh database) takes the longest, so give the login check ~15s.
  let passwordVerified = false;
  for (let attempt = 0; attempt < 15 && !passwordVerified; attempt += 1) {
    passwordVerified = await verifyLogin(port, credentials.username, credentials.password);
    if (!passwordVerified) {
      await new Promise((resolve) => setTimeout(resolve, 1000));
    }
  }

  if (output) {
    output.appendLine(
      passwordVerified
        ? `[lakehouse] stack is up. Warehouse UI: http://localhost:${port} (login ${credentials.username}/${credentials.password})`
        : `[lakehouse] stack is up. Warehouse UI: http://localhost:${port} — could not verify credentials; check ${credentials.file}`
    );
  }

  return {
    runtime,
    composeFile,
    uiUrl: `http://localhost:${port}`,
    username: credentials.username,
    password: credentials.password,
    passwordVerified,
    credentialsFile: credentials.file,
  };
}

async function stopLakehouse(pool, output) {
  const runtime = await detectRuntime();

  if (!runtime) {
    throw new Error('Neither Docker nor Podman was found.');
  }

  const composeFile = getComposeFilePath(pool.name);

  if (!fs.existsSync(composeFile)) {
    return { stopped: false };
  }

  const result = await exec(runtime, await composeArgs(composeFile, getComposeProjectName(pool.name), ['down']), 120000);

  if (!result.ok) {
    throw new Error(`${runtime} compose down failed: ${(result.stderr || result.error.message).trim()}`);
  }

  await refreshStackStatus(pool.name, await getUiPort(pool));

  if (output) {
    output.appendLine(`[lakehouse] stack stopped for pool "${pool.name}".`);
  }

  return { stopped: true };
}

function getCachedRuntime() {
  return runtimeCache.runtime;
}

// Last known UI port for display/links; falls back to the conventional 8080.
function getCachedUiPort() {
  return stackStatusCache.port || UI_PORT;
}

module.exports = {
  UI_PORT,
  detectRuntime,
  getCachedRuntime,
  refreshStackStatus,
  getCachedStackStatus,
  getCachedUiPort,
  getCredentialsFilePath,
  launchLakehouse,
  stopLakehouse,
  getComposeFilePath,
  buildComposeYaml,
};
