// Builds the executable Python script for a target notebook cell: chains prior
// cells for context, expands %run includes, and translates Databricks magics
// (%sql, %sh, %pip, %md, %fs) into plain Python.

const fs = require('node:fs/promises');
const path = require('node:path');
const vscode = require('vscode');
const {
  RUN_MAGIC_REGEX,
  SQL_MAGIC_REGEX,
  SH_MAGIC_REGEX,
  PIP_MAGIC_REGEX,
  MD_MAGIC_REGEX,
  FS_MAGIC_REGEX,
} = require('./constants');
const {
  parseNotebookText,
  parseNotebookFromNotebookDocument,
  getMagicContent,
  collectCellBodyLines,
  isExecutableNotebookCell,
  indentLines,
  escapeForDoubleQuotedPython,
  findCellIndexForLine,
} = require('./parser');
const pyResources = require('./pyResources');
const { getConfiguration } = require('./config');
const state = require('./state');

async function buildScriptForDocument(document, output, line) {
    const parsed = parseNotebookText(
        document.uri.fsPath,
        document.getText()
    );

    if (!parsed.isNotebookSource) {
        void vscode.window.showWarningMessage(
            'The active file is not a Databricks notebook-source Python file.'
        );
        return undefined;
    }

    const cellIndex =
        typeof line === 'number'
            ? findCellIndexForLine(parsed.cells, line)
            : parsed.cells.length - 1;

    return buildScriptForParsedNotebook(
        parsed.notebookPath,
        parsed.cells,
        output,
        cellIndex,
        undefined,
        {
            includePriorContext: true
        }
    );
}

async function buildScriptForNotebookDocument(
    notebook,
    output,
    cellIndex
) {
    const parsed = parseNotebookFromNotebookDocument(notebook);

    return buildScriptForParsedNotebook(
        parsed.notebookPath,
        parsed.cells,
        output,
        cellIndex,
        undefined,
        {
            includePriorContext: false
        }
    );
}

async function buildScriptForParsedNotebook(
    notebookPath,
    cells,
    output,
    line,
    sharedState,
    options
) {
    const includePriorContext =
        options &&
        Object.prototype.hasOwnProperty.call(
            options,
            'includePriorContext'
        )
            ? Boolean(options.includePriorContext)
            : true;

    const injectBootstrap =
        options &&
        Object.prototype.hasOwnProperty.call(
            options,
            'injectBootstrap'
        )
            ? Boolean(options.injectBootstrap)
            : getConfiguration().injectDatabricksBootstrap;

    const replayExecutedCellIndices =
        options && Array.isArray(options.replayExecutedCellIndices)
            ? options.replayExecutedCellIndices
            : [];

    const context = {
        output,
        injectBootstrap,
        unresolvedRunTargets: new Set(),
        includeCache:
            sharedState && sharedState.includeCache
                ? sharedState.includeCache
                : state.globalIncludeCache,
    };

    const targetNotebookCellIndex =
        typeof line === 'number'
            ? line
            : cells.length > 0
                ? cells[cells.length - 1].index
                : -1;

    const cellByIndex = new Map(
        cells.map((cell) => [cell.index, cell])
    );

    const selectedCell = cellByIndex.get(targetNotebookCellIndex);

    if (targetNotebookCellIndex < 0 || !selectedCell) {
        void vscode.window.showWarningMessage(
            'No Databricks notebook cell was found at the current cursor position.'
        );
        return undefined;
    }

    const lines = [];

    lines.push(
        `# Generated by Spark Cell Runner from ${path.basename(notebookPath)}`
    );
    lines.push('');

    if (context.injectBootstrap) {
        lines.push(...(await pyResources.buildBootstrapCode()).split('\n'));
        lines.push('');
    }

    lines.push('try:');

    const notebookContext = { notebookPath };

    const replayCells = replayExecutedCellIndices
        .map((index) => cellByIndex.get(index))
        .filter(Boolean);

    const replayCellIndexSet = new Set(
        replayCells.map((cell) => cell.index)
    );

    const baseCellsToExecute = includePriorContext
        ? cells.filter(
              (cell) => cell.index <= targetNotebookCellIndex
          )
        : [selectedCell];

    const seenCellIndices = new Set();

    const cellsToExecute = [
        ...replayCells,
        ...baseCellsToExecute.filter((cell) => {
            if (!cell || seenCellIndices.has(cell.index)) {
                return false;
            }

            seenCellIndices.add(cell.index);
            return true;
        }),
    ].sort((left, right) => left.index - right.index);

    const executedCellIndices = cellsToExecute
        .filter((cell) => isExecutableNotebookCell(cell))
        .map((cell) => cell.index);

    for (const cell of cellsToExecute) {
        const expanded = await expandCell(
            notebookContext,
            cell,
            context,
            new Set()
        );

        const isReplayCell =
            replayCellIndexSet.has(cell.index) &&
            cell.index !== targetNotebookCellIndex;

        lines.push(
            `    # Cell ${cell.index + 1}${isReplayCell ? ' (replay)' : ''}`
        );

        if (isReplayCell) {
            lines.push(
                '    import contextlib as __dcr_contextlib, io as __dcr_io;'
            );
            lines.push(
                '    with __dcr_contextlib.redirect_stdout(__dcr_io.StringIO()), __dcr_contextlib.redirect_stderr(__dcr_io.StringIO()):'
            );
            lines.push(...indentLines(expanded, 8));
        } else {
            lines.push(...indentLines(expanded, 4));
        }

        lines.push('');
    }

    lines.push('except DCRNotebookExit as __dcr_notebook_exit:');

    // RECONSTRUCTED fields: the original snapshot returned only {script,
    // executedCellIndices}, but runNotebookCells reads the metadata below to write
    // temp scripts and paint run-state decorations. Names for the temp files are
    // new; adjust freely.
    const fileStem = path.basename(notebookPath).replace(/\.py$/i, '');

    return {
        script: lines.join('\n'),
        executedCellIndices,
        cellIndex: targetNotebookCellIndex,
        statusLine: selectedCell.startLine,
        endLine: selectedCell.endLine,
        label: `Databricks cell ${targetNotebookCellIndex + 1}`,
        fileName: `${fileStem}.cell-${targetNotebookCellIndex + 1}.py`,
        resultFileName: `${fileStem}.cell-${targetNotebookCellIndex + 1}.result.txt`,
        unresolvedRunTargets: Array.from(context.unresolvedRunTargets),
    };
}

async function expandCell(notebook, cell, context, visited) {
    const result = [];

    if (cell.kind === vscode.NotebookCellKind.Markup) {
        result.push(`# Markdown cell omitted: ${cell.lines.join(" ").trim()}`);
        return result;
    }

    const strippedMagicLines = cell.lines.map((line) => getMagicContent(line));

    const firstMagicLine = strippedMagicLines[0];

    const sqlMagicMatch = firstMagicLine
        ? firstMagicLine.match(SQL_MAGIC_REGEX)
        : undefined;

    if (sqlMagicMatch) {
        const sqlLines = collectCellBodyLines(cell.lines, sqlMagicMatch[1]);
        result.push(`__dcr_sql_df = sql(${JSON.stringify(sqlLines.join("\n"))})`);
        result.push("try:");
        result.push("    __dcr_sql_df.show(20, truncate=False)");
        result.push("except Exception:");
        result.push("    print(__dcr_sql_df)");
        return result;
    }

    const shMagicMatch = firstMagicLine
        ? firstMagicLine.match(SH_MAGIC_REGEX)
        : undefined;

    if (shMagicMatch) {
        const shellLines = collectCellBodyLines(cell.lines, shMagicMatch[1]);
        result.push("import subprocess");
        result.push(
            `subprocess.run(${JSON.stringify(shellLines.join("\n"))}, shell=True, check=True)`
        );
        return result;
    }

    const pipMagicMatch = firstMagicLine
        ? firstMagicLine.match(PIP_MAGIC_REGEX)
        : undefined;

    if (pipMagicMatch) {
        const pipLines = collectCellBodyLines(cell.lines, pipMagicMatch[1]);
        result.push("import subprocess");
        result.push("import sys");
        result.push(
            `_dcr_pip_command = ${JSON.stringify(pipLines.join(" "))}`
        );
        result.push("try:");
        result.push(
            "    _dcr_pip_command = _dcr_pip_command.format_map(globals())"
        );
        result.push("except Exception:");
        result.push("    pass");
        result.push(
            "_dcr_pip_args = dcr_translate_pip_command(_dcr_pip_command)"
        );
        result.push(
            'subprocess.run([sys.executable, "-m", "pip", *dcr_pip_args], check=True)'
        );
        return result;
    }

    const mdMagicMatch = firstMagicLine
        ? firstMagicLine.match(MD_MAGIC_REGEX)
        : undefined;

    if (mdMagicMatch) {
        const markdownLines = collectCellBodyLines(cell.lines, mdMagicMatch[1]);
        result.push(`# Markdown cell omitted: ${markdownLines.join(" ").trim()}`);
        return result;
    }

    const fsMagicMatch = firstMagicLine
        ? firstMagicLine.match(FS_MAGIC_REGEX)
        : undefined;

    if (fsMagicMatch) {
        const fsLines = collectCellBodyLines(cell.lines, fsMagicMatch[1]);
        result.push(
            `print("[spark-cell-runner] %fs passthrough not implemented: ${escapeForDoubleQuotedPython(fsLines.join(" "))}")`
        );
        return result;
    }

    for (const line of cell.lines) {
        const magicContent = getMagicContent(line);

        if (!magicContent) {
            result.push(line);
            continue;
        }

        const runMatch = magicContent.match(RUN_MAGIC_REGEX);

        if (runMatch) {
            const includePath = await resolveNotebookInclude(
                notebook.notebookPath,
                runMatch[1]
            );

            if (!includePath) {
                context.output.appendLine(
                    `[warn] Could not resolve %run target: ${runMatch[1]}`
                );
                context.unresolvedRunTargets.add(runMatch[1]);
                result.push(`# Unresolved %run ${runMatch[1]}`);
                continue;
            }

            const realPath = path.normalize(includePath);

            if (visited.has(realPath)) {
                context.output.appendLine(
                    `[warn] Skipping recursive %run include: ${realPath}`
                );
                result.push(`# Skipped recursive %run ${realPath}`);
                continue;
            }

            visited.add(realPath);

            const cacheEntry = context.includeCache.get(realPath);
            let includedNotebook = cacheEntry
                ? cacheEntry.notebook
                : undefined;

            const stats = await fs.stat(realPath);
            const mtimeMs = stats.mtimeMs;

            if (
                !includedNotebook ||
                !cacheEntry ||
                cacheEntry.mtimeMs !== mtimeMs
            ) {
                const includedText = await fs.readFile(realPath, "utf8");
                includedNotebook = parseNotebookText(realPath, includedText);

                context.includeCache.set(realPath, {
                    notebook: includedNotebook,
                    mtimeMs,
                });
            }

            result.push(`# Begin %run ${runMatch[1]}`);

            for (const includedCell of includedNotebook.cells) {
                result.push(
                    ...(await expandCell(
                        includedNotebook,
                        includedCell,
                        context,
                        visited
                    ))
                );
                result.push("");
            }

            result.push("__dcr_wrap_logging_helpers()");
            result.push("__dcr_wrap_aladdin_config_reader()");
            result.push(`# End %run ${runMatch[1]}`);

            visited.delete(realPath);
            continue;
        }

        result.push(`# Unsupported MAGIC ${magicContent}`);
    }

    return result;
}

async function resolveNotebookInclude(baseNotebookPath, includeValue) {
    const raw = includeValue.trim().replace(/^[`"]|[`"]$/g, "");
    const baseDirectory = path.dirname(baseNotebookPath);
    const candidates = new Set();

    addNotebookPathCandidates(
        candidates,
        path.resolve(baseDirectory, raw)
    );

    if (raw.startsWith("/Workspace/")) {
        const workspaceRelative = raw.replace(/^\/Workspace\//, "");
        const workspaceSegments = workspaceRelative
            .split("/")
            .filter(Boolean);

        const localWorkspaceRoots =
            getLocalWorkspaceRoots(baseNotebookPath);

        for (const root of localWorkspaceRoots) {
            addNotebookPathCandidates(
                candidates,
                path.join(root, ...workspaceSegments)
            );
        }

        if (workspaceSegments.length > 1) {
            const [, ...withoutProjectRoot] = workspaceSegments;

            for (const root of localWorkspaceRoots) {
                addNotebookPathCandidates(
                    candidates,
                    path.join(root, ...withoutProjectRoot)
                );
            }
        }
    }

    for (const candidate of candidates) {
        try {
            const stats = await fs.stat(candidate);

            if (stats.isFile()) {
                return candidate;
            }
        } catch {
            // continue
        }
    }
}

function addNotebookPathCandidates(candidates, candidateBase) {
    candidates.add(path.normalize(candidateBase));
    if (!path.extname(candidateBase)) {
        candidates.add(path.normalize(`${candidateBase}.py`));
    }
}

function getLocalWorkspaceRoots(baseNotebookPath) {
    const roots = new Set();
    const workspaceFolders = vscode.workspace.workspaceFolders || [];

    for (const folder of workspaceFolders) {
        roots.add(folder.uri.fsPath);
    }

    let current = path.dirname(baseNotebookPath);
    roots.add(current);

    while (true) {
        const parent = path.dirname(current);

        if (parent === current) {
            break;
        }

        roots.add(parent);
        current = parent;
    }

    return Array.from(roots);
}

module.exports = {
    buildScriptForDocument,
    buildScriptForNotebookDocument,
    buildScriptForParsedNotebook,
    expandCell,
    resolveNotebookInclude,
};
